### PR TITLE
Fix bug in gradient computation

### PR DESCRIPTION
**Pull request by Micki-D**
This fixes a mistake I made in my previous PR

### CODE REVIEW

**Comment by oschulz** [comment]
Are the test failures related to this PR?

**Comment by Micki-D** [comment]
Yes, the failures are caused by this change, I am working on adjusting the tests, will push when ready

**Comment by oschulz** [comment]
Thanks!

**Comment by oschulz** [comment]
Good to merge?

**Comment by Micki-D** [comment]
Yes, should be good to merge!

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
